const data={
    products:[
        {
            _id:1,
            name:'Nike Slim Shirt',
            category:'shirt',
            image:'../images/p1.jpg',
            price:320,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality products',
        },
        {
            _id:2,
            name:'Adidas Slim Shirt',
            category:'shirt',
            image:'../images/p2.jpg',
            price:120,
            countInStock:20,
            brand:'Adidas',
            rating:4,
            numReviews:10,
            description:'high quality products',
        },
        {
            _id:3,
            name:'Lacoste Free Shirt',
            category:'shirt',
            image:'../images/p3.jpg',
            price:300,
            countInStock:0,
            brand:'Lacoste',
            rating:4.8,
            numReviews:17,
            description:'high quality products',
        },
        {
            _id:4,
            name:'Nike Slim Pants',
            category:'Pants',
            image:'../images/p4.jpg',
            price:320,
            countInStock:15,
            brand:'Nike',
            rating:4.5,
            numReviews:15,
            description:'high quality products',
        },
        {
            _id:5,
            name:'Puma Slim Pants',
            category:'Pant',
            image:'../images/p5.jpg',
            price:120,
            countInStock:0,
            brand:'puma',
            rating:4.6,
            numReviews:17,
            description:'high quality products',
        },
        {
            _id:6,
            name:'Addidas fit Shirt',
            category:'shirt',
            image:'../images/p6.jpg',
            price:220,
            countInStock:20,
            brand:'Nike',
            rating:4.7,
            numReviews:18,
            description:'high quality products',
        },
    ]
}

export default data;